### ISSUE TITLE
Assets should be cached

### ISSUE THREAD

**Issue by emibloque** [jesQM/stealthGame#3]
## Description

The main issue with #2 is not related to the new changes, but how media is being dealt with.
Each time you have to start/create an animation or a sound, you are requesting it through the network, and even though it is cached within the browser, it could take time to load a new resource.

![issue](https://user-images.githubusercontent.com/7079918/70195603-75b10700-1706-11ea-86f1-ea79f7ddaa78.gif)

## Solution

A possible solution to this was listed in the session _5 - Herramientas, framework y multijugador_ (and reminded by Jordan some days ago 🙈 ).

1. You need to go to your `Res.js` file and create a global array working as a cache:
    ```js
    const cache = []
    ```

2. When loading each image, you should store it in the cache, replacing the following:
    ```diff
    
    function cargarImagenes(indice){
    -    var imagenCargar = new Image();
    -    imagenCargar.src = rutasImagenes[indice];
    -    imagenCargar.onload = function(){
    +    cache[rutasImagenes[indice]] = new Image();
    +    cache[rutasImagenes[indice]].src = rutasImagenes[indice];
    +
    +    cache[rutasImagenes[indice]].onload = function(){
    ```     

3. Finally everywhere you create an image, replace them with the cache reference:
    ```diff
    class Modelo {
 
        constructor(imagenRuta, x, y) {
    -     this.imagen = new Image();
    -     this.imagen.src = imagenRuta;
    +     this.imagen = cache[imagenRuta];
          this.x = x;
          this.y = y;
          this.ancho = 
    ```     

You will need to do something similar for the audio, as it is a bit _chunky_.

**Comment by jesQM** [comment]
Well... it kinda works.
Sound aint that cut and animations (the one of going into a bush) does work every time.

However, looks like whenever a new pic is used (for example here, the player gets wounded and its picture changes), the onload is triggered, so the pics start being reloaded.
![Captura de pantalla (89)](https://user-images.githubusercontent.com/56931099/70217122-d9f0bc80-1740-11ea-8aae-9c74ad8b41f8.png)

The game just ends up reseting itself after iterating through all the assets.

To avoid this, I just changed the onload method once all pictures were loaded.
> function removeOnloadEvent() {
    for (let i = 0; i < rutasImagenes.length; i++) {
        cache[rutasImagenes[i]].onload = () => {};
    }
}

However, looks like the music is giving me some trouble. I did load it (in a different array to make it simpler), but, looks like the persecution theme wouldn't play the second time it was triggered (despite not being paused).

For now, that theme will not be cached.
